name: Main

on: push

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
          components: rustfmt
      - uses: actions/checkout@v1
      - run: cargo fmt --all -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: clippy
      - uses: actions/checkout@v1
      - run: cargo clippy --all-targets --all-features -- -D clippy::all

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@v1
      - run: cargo check --all

  test:
    needs: [codestyle, lint, compile]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, beta, nightly]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Test
      run: cargo test --verbose
    - name: Coverage
      if: matrix.rust == 'stable'
      run: |
        # tarpaulin knows how to extract data from ci
        # ci services and GitHub actions is not one of them
        # work around that by masquerading as travis
        # https://github.com/xd009642/coveralls-api/blob/6da4ccd7c6eaf1df04cfd1e560362de70fa80605/src/lib.rs#L247-L262
        export TRAVIS_JOB_ID=${GITHUB_SHA}
        export TRAVIS_PULL_REQUEST=false
        export TRAVIS_BRANCH=${GITHUB_REF##*/}
        cargo install cargo-tarpaulin
        cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [test]
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          - os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-musl
            bin: 'cliff'
            name: 'cliff-Linux-x86_64.tar.gz'
          - os: windows-latest
            rust: stable
            target: x86_64-pc-windows-msvc
            bin: 'cliff.exe'
            name: 'cliff-Windows-x86_64.zip'
          - os: macOS-latest
            rust: stable
            target: x86_64-apple-darwin
            bin: 'cliff'
            name: 'cliff-Darwin-x86_64.tar.gz'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
        targets: ${{ matrix.target }}
    - name: Setup musl-gcc
      if: contains(matrix.target, 'musl')
      run: |
        sudo apt-get install musl-tools
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
    - name: Package
      shell: bash
      run: |
        strip target/${{ matrix.target }}/release/${{ matrix.bin }}
        cd target/${{ matrix.target }}/release
        if [[ "${{ matrix.os }}" == "windows-latest" ]]
        then
          7z a ../../../${{ matrix.name }} ${{ matrix.bin }}
        else
          tar czvf ../../../${{ matrix.name }} ${{ matrix.bin }}
        fi
        cd -
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
          files: 'cliff*'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}